ignite:
  drivers:
    pusher:
      service_id: JRemmurd\IgniteBundle\Ignite\Driver\Pusher
      config:
        key: ################
        secret: ################
        id: #######
        options:
          cluster: eu
        log_to_console: true

    logger:
      service_id: JRemmurd\IgniteBundle\Ignite\Driver\Logger

    notification:
      service_id: JRemmurd\IgniteBundle\Ignite\Driver\Notification

  channels:
    strict_parameters: true
    default_driver_name: pusher
    #    factory_id: ignite.channel_factory

    namespaces:
      admin:
        default_driver_name: pusher
        authEndpoint: /admin/ignite/auth
        channels:
          presence:
          - name: user
            authenticator: ignite.authenticator.pimcore
            drivers: [logger, pusher]
          #              useSlugForJS: false # include parameters in js channel name
          private:
          - name: user_notifications
            authenticator: ignite.authenticator.pimcore
            drivers: [logger, pusher, notification]
            parameters:
            - id

      app:
        pattern: ^/ignite
        authEndpoint: /ignite/auth/{driver}
        channels:
          public:
          - name: global
            drivers: [logger, pusher]
          - name: notifications
            drivers: [logger, pusher, notification]

          # public channels do not necessarily be configured
          #          public:
          #            global:
          # drivers can be configured for each channel
          #              drivers:
          #                - logger
          #                - pusher

          # configuration for authenticated channels is required
          presence:
          - name: user
            parameters: # only valid js variable characters without _ --> used for building the channel name!
            - id
            authenticator: ignite.authenticator.user
            drivers: [logger, pusher]
